#+TITLE: HA's GNU Emacs LINUX MASTAR
#+AUTHOR: HUSSAIN ALMALKI (HA)
#+DESCRIPTION: DT's personal Emacs Linux Mastar.
#+STARTUP: showeverything
#+OPTIONS: toc:2

* TABLE OF CONTENTS :toc:
- [[#file-management-in-bash][File Management in BASH]]
  - [[#in-this-chapter][IN THIS CHAPTER]]
- [[#touch-and-mkdir][touch and mkdir]]
  - [[#touch][touch]]
  - [[#mkdir-make-directory][mkdir (make directory)]]
- [[#mv-and-cp][mv and cp]]
  - [[#mv-move][mv (move)]]
  - [[#cp-copy][cp (copy)]]
- [[#how-to-delete-files-and-folders][How to delete files and folders]]
  - [[#rm-remove][rm (remove)]]
- [[#exercise-file-management][Exercise: File management]]
  - [[#solution][SOLUTION:]]
- [[#filename-expansion-globbing][Filename expansion (globbing)]]
  - [[#filename-expansion][Filename expansion]]
  - [[#important][IMPORTANT:]]

* File Management in BASH
** IN THIS CHAPTER
- You will learn how to creat folders and files
- You will learn how to copy and move files
- You will learn how to delete files and how dangerous ~Bash~ can be (and how you can mitigate that)
- *In addition, you will solve some real-world problems*
  - Extracting photos from a folder structure (such as an SD-card from a camera)
  - And you will extract all Excel and PDF files from a nested folder structure
* touch and mkdir
** touch
- typical use case: create and empty file (or multiple files)
#+begin_src bash
root@5aaa26cbdddf:~# ls
root@5aaa26cbdddf:~# pwd
/root
root@5aaa26cbdddf:~# touch max.txt
root@5aaa26cbdddf:~# ls
max.txt
root@5aaa26cbdddf:~# touch andy.txt laura.txt
root@5aaa26cbdddf:~# ls
andy.txt  laura.txt  max.txt
root@5aaa26cbdddf:~#
#+end_src
- *more precisely*:
  - to modify the timestamp of a file
  - if the file already exists, only its timestamp will be modified
  - otherwise, a new (and empty) file is creatd
#+begin_src bash
root@5aaa26cbdddf:~# ls -l
total 0
-rw-r--r-- 1 root root 0 Jul 10 07:56 andy.txt
-rw-r--r-- 1 root root 0 Jul 10 07:56 laura.txt
-rw-r--r-- 1 root root 0 Jul 10 07:55 max.txt
root@5aaa26cbdddf:~# touch max.txt
root@5aaa26cbdddf:~# ls -l
total 0
-rw-r--r-- 1 root root 0 Jul 10 07:56 andy.txt
-rw-r--r-- 1 root root 0 Jul 10 07:56 laura.txt
-rw-r--r-- 1 root root 0 Jul 10 07:58 max.txt
root@5aaa26cbdddf:~#
#+end_src

** mkdir (make directory)
- create a new directory
#+begin_src bash
root@5aaa26cbdddf:~# ls
andy.txt  laura.txt  max.txt
root@5aaa26cbdddf:~# mkdir ready
root@5aaa26cbdddf:~# ls
andy.txt  laura.txt  max.txt  ready
root@5aaa26cbdddf:~# ls -la
total 20
drwx------ 1 root root 4096 Jul 10 07:59 .
drwxr-xr-x 1 root root 4096 Jul 10 07:53 ..
-rw-r--r-- 1 root root  571 Apr 10  2021 .bashrc
-rw-r--r-- 1 root root  161 Jul  9  2019 .profile
-rw-r--r-- 1 root root    0 Jul 10 07:56 andy.txt
-rw-r--r-- 1 root root    0 Jul 10 07:56 laura.txt
-rw-r--r-- 1 root root    0 Jul 10 07:58 max.txt
drwxr-xr-x 2 root root 4096 Jul 10 07:59 ready
root@5aaa26cbdddf:~# ls -l --color
total 4
-rw-r--r-- 1 root root    0 Jul 10 07:56 andy.txt
-rw-r--r-- 1 root root    0 Jul 10 07:56 laura.txt
-rw-r--r-- 1 root root    0 Jul 10 07:58 max.txt
drwxr-xr-x 2 root root 4096 Jul 10 07:59 ready
#+end_src

* mv and cp
** mv (move)
- move an existing file to another location
- can also be used to rename an existing file
#+begin_src bash
root@5aaa26cbdddf:~# ls
andy.txt  laura.txt  max.txt  ready
root@5aaa26cbdddf:~# mv andy.txt ready/
root@5aaa26cbdddf:~# ls
laura.txt  max.txt  ready
root@5aaa26cbdddf:~# ls ready/
andy.txt
root@5aaa26cbdddf:~# cd ready/
root@5aaa26cbdddf:~/ready# ls
andy.txt
root@5aaa26cbdddf:~/ready# cd ..
root@5aaa26cbdddf:~# mv max.txt maximilian.txt
root@5aaa26cbdddf:~# ls
laura.txt  maximilian.txt  ready
root@5aaa26cbdddf:~# mv maximilian.txt ready/max.txt
root@5aaa26cbdddf:~# ls ready/
andy.txt  max.txt
root@5aaa26cbdddf:~#
#+end_src

** cp (copy)
- to copy an existing file
- cp -R: copies a whole folder
#+begin_src bash
root@5aaa26cbdddf:~# ls
laura.txt  ready
root@5aaa26cbdddf:~# cp laura.txt ready/
root@5aaa26cbdddf:~# ls ready/
andy.txt  laura.txt  max.txt
root@5aaa26cbdddf:~# cp ready/max.txt .
root@5aaa26cbdddf:~# ls
laura.txt  max.txt  ready
root@5aaa26cbdddf:~# cp ready/max.txt max_bak.txt
root@5aaa26cbdddf:~# ls
laura.txt  max.txt  max_bak.txt  ready
root@5aaa26cbdddf:~# cp -R ready/ ready_bak
root@5aaa26cbdddf:~# ls -l
total 8
-rw-r--r-- 1 root root    0 Jul 10 07:56 laura.txt
-rw-r--r-- 1 root root    0 Jul 10 08:07 max.txt
-rw-r--r-- 1 root root    0 Jul 10 08:07 max_bak.txt
drwxr-xr-x 2 root root 4096 Jul 10 08:07 ready
drwxr-xr-x 2 root root 4096 Jul 10 08:08 ready_bak
root@5aaa26cbdddf:~# ls ready_1/
andy.txt  laura.txt  max.txt
#+end_src

* How to delete files and folders
** rm (remove)
- to remove a file (or multiple files at once)
- for deleting a directory, you need to use the option -r
  - works for empty and non-empty directories
#+begin_src bash
root@5aaa26cbdddf:~# ls
laura.txt  max.txt  max_bak.txt  ready	ready_bak
root@5aaa26cbdddf:~# rm max_bak.txt
root@5aaa26cbdddf:~# ls
laura.txt  max.txt  ready  ready_bak
root@5aaa26cbdddf:~# rm -r ready_bak/
root@5aaa26cbdddf:~# ls
laura.txt  max.txt  ready
#+end_src

* Exercise: File management
- In the next lecture, I will present you an exercise.
- It's pretty much just a play-along to do some file management.
- *The goal is*:
  - You can prectice the file management commands for Bash.
  - You can use a file browser to see what each command does and how those commands work.
  - So please don't just execute the commands, also have a look at what they do and how they change the files!
- *Outlook*:
  - Later exercises in thsi course will be more practical, but we need to practice the basice first.
** SOLUTION:
#+begin_src bash
root@5aaa26cbdddf:/# pwd
/
root@5aaa26cbdddf:/# cd /root
root@5aaa26cbdddf:~# pwd
/root
root@5aaa26cbdddf:~# ls -l
total 4
-rw-r--r-- 1 root root    0 Jul 10 07:56 laura.txt
-rw-r--r-- 1 root root    0 Jul 10 08:07 max.txt
drwxr-xr-x 2 root root 4096 Jul 10 08:07 ready
root@5aaa26cbdddf:~# mkdir tmp_website
root@5aaa26cbdddf:~# cd tmp_website/
root@5aaa26cbdddf:~/tmp_website# pwd
/root/tmp_website
root@5aaa26cbdddf:~/tmp_website# touch index.html style.css script.js
root@5aaa26cbdddf:~/tmp_website# ls
index.html  script.js  style.css
root@5aaa26cbdddf:~/tmp_website# mkdir styles
root@5aaa26cbdddf:~/tmp_website# mv style.css styles
root@5aaa26cbdddf:~/tmp_website# ls
index.html  script.js  styles
root@5aaa26cbdddf:~/tmp_website# ls -l
total 4
-rw-r--r-- 1 root root    0 Jul 12 08:13 index.html
-rw-r--r-- 1 root root    0 Jul 12 08:13 script.js
drwxr-xr-x 2 root root 4096 Jul 12 08:13 styles
root@5aaa26cbdddf:~/tmp_website# ls styles/
style.css
root@5aaa26cbdddf:~/tmp_website# pwd
/root/tmp_website
root@5aaa26cbdddf:~/tmp_website# mkdir scripts
root@5aaa26cbdddf:~/tmp_website# ls -l
total 8
-rw-r--r-- 1 root root    0 Jul 12 08:13 index.html
-rw-r--r-- 1 root root    0 Jul 12 08:13 script.js
drwxr-xr-x 2 root root 4096 Jul 12 08:14 scripts
drwxr-xr-x 2 root root 4096 Jul 12 08:13 styles
root@5aaa26cbdddf:~/tmp_website# mv script.js scripts/index.js
root@5aaa26cbdddf:~/tmp_website# ls scripts/
index.js
root@5aaa26cbdddf:~/tmp_website# mkdir pages
root@5aaa26cbdddf:~/tmp_website# touch pages/page1.html
root@5aaa26cbdddf:~/tmp_website# ls pages/
page1.html
root@5aaa26cbdddf:~/tmp_website# cp pages/page1.html pages/page2.html
root@5aaa26cbdddf:~/tmp_website# ls pages/
page1.html  page2.html
root@5aaa26cbdddf:~/tmp_website# ls
index.html  pages  scripts  styles
root@5aaa26cbdddf:~/tmp_website# mv pages/page2.html .
root@5aaa26cbdddf:~/tmp_website# ls
index.html  page2.html	pages  scripts	styles
root@5aaa26cbdddf:~/tmp_website#
root@5aaa26cbdddf:~/tmp_website# rm index.html pages/page1.html
root@5aaa26cbdddf:~/tmp_website# ls
page2.html  pages  scripts  styles
root@5aaa26cbdddf:~/tmp_website# ls pages/
root@5aaa26cbdddf:~/tmp_website#
root@5aaa26cbdddf:~/tmp_website# mv page2.html index.html
root@5aaa26cbdddf:~/tmp_website# ls
index.html  pages  scripts  styles
root@5aaa26cbdddf:~/tmp_website# rmdir pages/
root@5aaa26cbdddf:~/tmp_website# ls -la
total 16
drwxr-xr-x 4 root root 4096 Jul 12 08:20 .
drwx------ 1 root root 4096 Jul 12 08:12 ..
-rw-r--r-- 1 root root    0 Jul 12 08:17 index.html
drwxr-xr-x 2 root root 4096 Jul 12 08:15 scripts
drwxr-xr-x 2 root root 4096 Jul 12 08:13 styles
root@5aaa26cbdddf:~/tmp_website# cd ..
root@5aaa26cbdddf:~# rm -r tmp_website/
root@5aaa26cbdddf:~# ls
laura.txt  max.txt  ready
root@5aaa26cbdddf:~#
#+end_src
* Filename expansion (globbing)
** Filename expansion
- Bash can rewrite our command before it is being executed.
- Globbing recongnizes and expands pre-defined wildcard characters.
- It will then search for files that match this pattern and expand (rewrite) out command.
- Thsi allows us to easily access multiple files.
#+begin_src bash
root@5aaa26cbdddf:~# ls
root@5aaa26cbdddf:~# touch IMG_2004.jpg IMG_6423.jpg IMG_6662.jpg IMG_6677.MOV IMG_6677.SRT
root@5aaa26cbdddf:~# ls
IMG_2004.jpg  IMG_6423.jpg  IMG_6662.jpg  IMG_6677.MOV	IMG_6677.SRT
root@5aaa26cbdddf:~# mkdir images
root@5aaa26cbdddf:~# mv IMG_2004.jpg IMG_6423.jpg IMG_6662.jpg images/
root@5aaa26cbdddf:~# ls
IMG_6677.MOV  IMG_6677.SRT  images
root@5aaa26cbdddf:~# ls images/
IMG_2004.jpg  IMG_6423.jpg  IMG_6662.jpg
root@5aaa26cbdddf:~# mv images/IMG_2004.jpg images/IMG_6423.jpg images/IMG_6662.jpg .
root@5aaa26cbdddf:~# ls
IMG_2004.jpg  IMG_6423.jpg  IMG_6662.jpg  IMG_6677.MOV	IMG_6677.SRT  images
#+end_src
- *Wildcard character:* *
  - Matches 0 to any number of characters.
#+begin_src bash
root@5aaa26cbdddf:~# ls
IMG_2004.jpg  IMG_6423.jpg  IMG_6662.jpg  IMG_6677.MOV	IMG_6677.SRT  images
root@5aaa26cbdddf:~# mv *.jpg images/
root@5aaa26cbdddf:~# ls images/
IMG_2004.jpg  IMG_6423.jpg  IMG_6662.jpg
root@5aaa26cbdddf:~# ls
IMG_6677.MOV  IMG_6677.SRT  images
root@5aaa26cbdddf:~# mv images/*.jpg .
root@5aaa26cbdddf:~# ls
IMG_2004.jpg  IMG_6423.jpg  IMG_6662.jpg  IMG_6677.MOV	IMG_6677.SRT  images
root@5aaa26cbdddf:~# echo *.jpg
IMG_2004.jpg IMG_6423.jpg IMG_6662.jpg
root@5aaa26cbdddf:~# ls *.jpg
IMG_2004.jpg  IMG_6423.jpg  IMG_6662.jpg
root@5aaa26cbdddf:~# echo '*.jpg'
*.jpg
root@5aaa26cbdddf:~# echo *
IMG_2004.jpg IMG_6423.jpg IMG_6662.jpg IMG_6677.MOV IMG_6677.SRT images
#+end_src

** IMPORTANT:
- The wildcard characters must not be quoted (so neither in 'single quotes' nor "double quotes").
- Globbing does not use regular expressions.
